-- =====================================================
-- game_feedbacks 테이블 완전 재생성 스크립트
-- =====================================================

-- 1단계: 기존 game_feedbacks 테이블 삭제
DROP TABLE IF EXISTS game_feedbacks CASCADE;

-- 2단계: 올바른 스키마로 game_feedbacks 테이블 재생성
CREATE TABLE game_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    game_id VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL,
    engagement INTEGER NOT NULL,
    difficulty INTEGER NOT NULL,
    comment TEXT,
    actual_participants INTEGER NOT NULL,
    actual_duration INTEGER,
    submitted_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    organizer_notes TEXT
);

-- 3단계: 확인용 쿼리
SELECT 'game_feedbacks columns' as info, 
       column_name, 
       data_type 
FROM information_schema.columns 
WHERE table_name = 'game_feedbacks' 
ORDER BY column_name;

-- 완료 메시지
DO $$
BEGIN
    RAISE NOTICE 'game_feedbacks 테이블이 올바르게 재생성되었습니다!';
    RAISE NOTICE '이제 백엔드 애플리케이션을 재시작하세요.';
END $$;
